// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjtjz0KCYCJ7vTt5foVE5-Lkm9MrvD_48',
    appId: '1:240109347323:web:74cd07d00921ae37d4eb5e',
    messagingSenderId: '240109347323',
    projectId: 'emart-94526',
    authDomain: 'emart-94526.firebaseapp.com',
    storageBucket: 'emart-94526.firebasestorage.app',
    measurementId: 'G-WCT8QSKJWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs2Iu4wCi2LJqYf2gTbPxp50Dzoa1DECM',
    appId: '1:240109347323:android:0658deec5c778565d4eb5e',
    messagingSenderId: '240109347323',
    projectId: 'emart-94526',
    storageBucket: 'emart-94526.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR1RYHI5MhabjrdfY6sd8FtPrzh1rGztQ',
    appId: '1:240109347323:ios:d75a5d250498a905d4eb5e',
    messagingSenderId: '240109347323',
    projectId: 'emart-94526',
    storageBucket: 'emart-94526.firebasestorage.app',
    iosBundleId: 'com.example.emartApp',
  );
}
